2019-11-29 14:41:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ [42102-197]
2019-11-29 14:42:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ [42102-197]
2019-11-29 14:44:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ [42102-197]
2019-11-29 14:44:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ [42102-197]
2019-11-29 14:44:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ [42102-197]
2019-11-29 14:44:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ [42102-197]
2019-11-29 14:44:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ [42102-197]
2019-11-29 14:44:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ [42102-197]
2019-11-29 14:44:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ [42102-197]
2019-11-29 14:44:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ [42102-197]
2019-11-29 14:44:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ [42102-197]
2019-11-29 14:44:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ [42102-197]
2019-11-29 14:49:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ [42102-197]
2019-11-29 15:13:15 jdbc[14]: null
org.h2.message.DbException: La conexi贸n no fue cerrada por la aplicaci贸n y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:197)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:137)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:699)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:685)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: La conexi贸n no fue cerrada por la aplicaci贸n y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-11-29 15:45:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ where user0_.USERNAME=? [42102-197]
2019-11-29 15:52:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ where user0_.USERNAME=? [42102-197]
2019-11-29 15:55:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ where user0_.USERNAME=? [42102-197]
2019-11-29 16:06:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select user0_.ID as ID1_4_, user0_.EMAIL as EMAIL2_4_, user0_.FIRSTNAME as FIRSTNAM3_4_, user0_.LASTNAME as LASTNAME4_4_, user0_.PASSWORD as PASSWORD5_4_, user0_.PHONE as PHONE6_4_, user0_.USERNAME as USERNAME7_4_ from USER user0_ where user0_.USERNAME=? [42102-197]
